"""initial schema - all tables

Revision ID: a1b2c3d4e5f6
Revises:
Create Date: 2026-07-16 00:00:00

This was hand-written from the SQLAlchemy models in app/models/, not
autogenerated - there's no live database in this environment to run
`alembic revision --autogenerate` against. Double-check it against your
actual MySQL version (this targets utf8mb4 / InnoDB defaults) before running
it against a database that matters, and diff it against a fresh
autogenerate once you have a real DB connection, just in case.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "a1b2c3d4e5f6"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _timestamps():
    """created_at/updated_at pair used on every table (TimestampMixin)."""
    return [
        sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.func.now(),
            nullable=False,
        ),
    ]


def _soft_delete():
    """deleted_at column used by every table with SoftDeleteMixin."""
    return [sa.Column("deleted_at", sa.DateTime(), nullable=True)]


def upgrade() -> None:
    # -- users -----------------------------------------------------------
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("name", sa.String(255), nullable=True),
        sa.Column("email", sa.String(255), nullable=True),
        sa.Column("password", sa.String(255), nullable=True),
        sa.Column("cellphone", sa.String(32), nullable=True),
        sa.Column("otp", sa.String(16), nullable=True),
        sa.Column("login_token", sa.String(255), nullable=True),
        sa.Column("is_admin", sa.SmallInteger(), server_default="0", nullable=False),
        *_timestamps(),
        *_soft_delete(),
        sa.UniqueConstraint("email", name="uq_users_email"),
        sa.UniqueConstraint("cellphone", name="uq_users_cellphone"),
    )

    # -- access_tokens (replaces Sanctum's personal_access_tokens) --------
    op.create_table(
        "access_tokens",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column(
            "user_id", sa.Integer(),
            sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False,
        ),
        sa.Column("token_hash", sa.String(255), nullable=False),
        sa.Column("name", sa.String(255), server_default="myApp", nullable=False),
        sa.Column("abilities", sa.JSON(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
        sa.UniqueConstraint("token_hash", name="uq_access_tokens_token_hash"),
    )
    op.create_index("ix_access_tokens_user_id", "access_tokens", ["user_id"])

    # -- provinces / cities ------------------------------------------------
    op.create_table(
        "provinces",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("name", sa.String(255), nullable=False),
        *_timestamps(),
        *_soft_delete(),
    )
    op.create_table(
        "cities",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column(
            "province_id", sa.Integer(),
            sa.ForeignKey("provinces.id", ondelete="CASCADE"), nullable=False,
        ),
        *_timestamps(),
        *_soft_delete(),
    )

    # -- categories (self-referencing parent/child) -----------------------
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column(
            "parent_id", sa.Integer(),
            sa.ForeignKey("categories.id", ondelete="SET NULL"), nullable=True,
        ),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("description", sa.String(255), nullable=True),
        sa.Column("image", sa.String(255), nullable=True),
        *_timestamps(),
        *_soft_delete(),
    )

    # -- user_addresses ------------------------------------------------------
    op.create_table(
        "user_addresses",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("title", sa.String(255), nullable=False),
        sa.Column("address", sa.String(255), nullable=False),
        sa.Column("cellphone", sa.String(32), nullable=False),
        sa.Column("postal_code", sa.String(32), nullable=False),
        sa.Column(
            "user_id", sa.Integer(),
            sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False,
        ),
        # plain bigint, no FK - matches the original Laravel migration exactly
        sa.Column("province_id", sa.BigInteger(), nullable=False),
        sa.Column("city_id", sa.BigInteger(), nullable=False),
        *_timestamps(),
        *_soft_delete(),
    )

    # -- products / images / colors / sizes --------------------------------
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("slug", sa.String(255), nullable=False),
        sa.Column(
            "category_id", sa.Integer(),
            sa.ForeignKey("categories.id", ondelete="CASCADE"), nullable=False,
        ),
        sa.Column("primary_image", sa.String(255), nullable=False),
        sa.Column("primary_image_blurDataURL", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("price", sa.Integer(), server_default="0", nullable=False),
        sa.Column("quantity", sa.Integer(), server_default="0", nullable=False),
        sa.Column("status", sa.SmallInteger(), server_default="1", nullable=False),
        sa.Column("sale_price", sa.Integer(), server_default="0", nullable=False),
        sa.Column("date_on_sale_from", sa.DateTime(), nullable=True),
        sa.Column("date_on_sale_to", sa.DateTime(), nullable=True),
        *_timestamps(),
        *_soft_delete(),
        sa.UniqueConstraint("slug", name="uq_products_slug"),
    )
    op.create_table(
        "product_images",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column(
            "product_id", sa.Integer(),
            sa.ForeignKey("products.id", ondelete="CASCADE"), nullable=False,
        ),
        sa.Column("image", sa.String(255), nullable=False),
        *_timestamps(),
        *_soft_delete(),
    )
    op.create_table(
        "product_colors",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column(
            "product_id", sa.Integer(),
            sa.ForeignKey("products.id", ondelete="CASCADE"), nullable=False,
        ),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("color_code", sa.String(32), nullable=False),
        sa.Column("image", sa.String(255), nullable=False),
        *_timestamps(),
        *_soft_delete(),
    )
    op.create_table(
        "product_sizes",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column(
            "product_color_id", sa.Integer(),
            sa.ForeignKey("product_colors.id", ondelete="CASCADE"), nullable=False,
        ),
        sa.Column("size", sa.String(32), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), server_default="0", nullable=False),
        *_timestamps(),
        *_soft_delete(),
    )

    # -- coupons / shipping_methods ----------------------------------------
    op.create_table(
        "coupons",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("code", sa.String(255), nullable=False),
        sa.Column("percentage", sa.Integer(), nullable=False),
        sa.Column("expired_at", sa.DateTime(), nullable=False),
        *_timestamps(),
        *_soft_delete(),
        sa.UniqueConstraint("code", name="uq_coupons_code"),
    )
    op.create_table(
        "shipping_methods",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("delivery_days", sa.SmallInteger(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.true(), nullable=False),
        *_timestamps(),
        *_soft_delete(),
    )

    # -- orders / order_items ------------------------------------------------
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column(
            "user_id", sa.Integer(),
            sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False,
        ),
        sa.Column(
            "address_id", sa.Integer(),
            sa.ForeignKey("user_addresses.id", ondelete="CASCADE"), nullable=False,
        ),
        sa.Column(
            "coupon_id", sa.Integer(),
            sa.ForeignKey("coupons.id", ondelete="CASCADE"), nullable=True,
        ),
        sa.Column(
            "shipping_method_id", sa.Integer(),
            sa.ForeignKey("shipping_methods.id", ondelete="SET NULL"), nullable=True,
        ),
        sa.Column("status", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("order_status", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("total_amount", sa.Integer(), nullable=False),
        sa.Column("coupon_amount", sa.Integer(), server_default="0", nullable=False),
        sa.Column("shipping_amount", sa.Integer(), server_default="0", nullable=False),
        sa.Column("paying_amount", sa.Integer(), nullable=False),
        sa.Column("payment_status", sa.SmallInteger(), server_default="0", nullable=False),
        *_timestamps(),
        *_soft_delete(),
    )
    op.create_table(
        "order_items",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column(
            "order_id", sa.Integer(),
            sa.ForeignKey("orders.id", ondelete="CASCADE"), nullable=False,
        ),
        sa.Column(
            "product_id", sa.Integer(),
            sa.ForeignKey("products.id", ondelete="CASCADE"), nullable=False,
        ),
        sa.Column(
            "product_color_id", sa.Integer(),
            sa.ForeignKey("product_colors.id", ondelete="SET NULL"), nullable=True,
        ),
        sa.Column(
            "product_size_id", sa.Integer(),
            sa.ForeignKey("product_sizes.id", ondelete="SET NULL"), nullable=True,
        ),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("subtotal", sa.Integer(), nullable=False),
        *_timestamps(),
        *_soft_delete(),
    )

    # -- transactions --------------------------------------------------------
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column(
            "user_id", sa.Integer(),
            sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False,
        ),
        sa.Column(
            "order_id", sa.Integer(),
            sa.ForeignKey("orders.id", ondelete="CASCADE"), nullable=False,
        ),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(255), nullable=True),
        sa.Column("trans_id", sa.String(255), nullable=True),
        sa.Column("status", sa.SmallInteger(), server_default="0", nullable=False),
        *_timestamps(),
        *_soft_delete(),
    )

    # -- contact_us / sliders / stories --------------------------------------
    op.create_table(
        "contact_us",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("name", sa.String(255), nullable=False),
        sa.Column("email", sa.String(255), nullable=False),
        sa.Column("subject", sa.String(255), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        *_timestamps(),
        *_soft_delete(),
    )
    op.create_table(
        "sliders",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("title", sa.String(255), nullable=True),
        sa.Column("file", sa.String(255), nullable=False),
        sa.Column("link", sa.String(255), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.true(), nullable=False),
        sa.Column("sort", sa.SmallInteger(), server_default="0", nullable=False),
        *_timestamps(),
        *_soft_delete(),
    )
    op.create_table(
        "stories",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("title", sa.String(255), nullable=True),
        sa.Column("type", sa.Enum("image", "video", name="story_type"), nullable=False),
        sa.Column("file", sa.String(255), nullable=False),
        sa.Column("thumbnail", sa.String(255), nullable=True),
        sa.Column("caption", sa.Text(), nullable=True),
        sa.Column("link_url", sa.String(255), nullable=True),
        sa.Column("link_label", sa.String(255), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default=sa.true(), nullable=False),
        sa.Column("sort", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        *_timestamps(),
        *_soft_delete(),
    )

    # -- carts / cart_items (new - no Laravel equivalent) --------------------
    op.create_table(
        "carts",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column(
            "user_id", sa.Integer(),
            sa.ForeignKey("users.id", ondelete="CASCADE"), nullable=False,
        ),
        *_timestamps(),
        sa.UniqueConstraint("user_id", name="uq_carts_user_id"),
    )
    op.create_table(
        "cart_items",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column(
            "cart_id", sa.Integer(),
            sa.ForeignKey("carts.id", ondelete="CASCADE"), nullable=False,
        ),
        sa.Column(
            "product_id", sa.Integer(),
            sa.ForeignKey("products.id", ondelete="CASCADE"), nullable=False,
        ),
        sa.Column(
            "product_color_id", sa.Integer(),
            sa.ForeignKey("product_colors.id", ondelete="CASCADE"), nullable=True,
        ),
        sa.Column(
            "product_size_id", sa.Integer(),
            sa.ForeignKey("product_sizes.id", ondelete="CASCADE"), nullable=True,
        ),
        sa.Column("quantity", sa.Integer(), server_default="1", nullable=False),
        *_timestamps(),
        sa.UniqueConstraint(
            "cart_id", "product_id", "product_color_id", "product_size_id",
            name="uq_cart_item_variant",
        ),
    )


def downgrade() -> None:
    # reverse dependency order
    op.drop_table("cart_items")
    op.drop_table("carts")
    op.drop_table("stories")
    op.drop_table("sliders")
    op.drop_table("contact_us")
    op.drop_table("transactions")
    op.drop_table("order_items")
    op.drop_table("orders")
    op.drop_table("shipping_methods")
    op.drop_table("coupons")
    op.drop_table("product_sizes")
    op.drop_table("product_colors")
    op.drop_table("product_images")
    op.drop_table("products")
    op.drop_table("user_addresses")
    op.drop_table("categories")
    op.drop_table("cities")
    op.drop_table("provinces")
    op.drop_index("ix_access_tokens_user_id", table_name="access_tokens")
    op.drop_table("access_tokens")
    op.drop_table("users")
